export type Lang = "en" | "zh";

export const copy = {
  zh: {
    brand: "斯威夫特论坛",
    brandMark: "TS",
    navConcerts: "最近演唱会",
    navWhy: "我们为什么爱她",
    signIn: "登录",
    signOut: "退出",
    langEn: "EN",
    langZh: "中文",
    langAria: "切换语言",
    heroKicker: "霉粉社区",
    heroTitle: "给热爱她的人",
    heroLead:
      "时代巡回的灯还亮着。这里记下最近的演唱会，也写下我们为什么一次次被泰勒·斯威夫特打动。",
    heroCtaConcerts: "最近演唱会",
    heroCtaWhy: "我们为什么爱她",
    concertsKicker: "The Eras Tour",
    concertsTitle: "最近的演唱会",
    concertsLead:
      "时代巡回于 2024 年 12 月 8 日在温哥华落下最后一弓。一百四十九场之后，灯光还在腕带上闪。目前没有已公布的 2026 巡演日期——但那场终场，已经变成可以反复走进的电影。",
    concertsStatShows: "场演出",
    concertsStatCities: "座城市",
    concertsStatCountries: "个国家",
    concertsStatContinents: "大洲",
    featuredBadge: "终场",
    featuredCity: "温哥华",
    featuredVenue: "BC Place Stadium",
    featuredDate: "2024 年 12 月 8 日",
    featuredTitle: "时代巡回的最后一夜",
    featuredBody:
      "二十一个月、五片大陆之后，泰勒在温哥华的雨夜里谢幕。惊喜歌、 Tortured Poets 整段、以及那句几乎被唱成誓言的 Long Live——终场不是结束，是把整段旅程交还给听众。2025 年 12 月，迪士尼推出纪录片《The End of an Era》与完整演唱会电影《The Final Show》，把那一夜的灯光重新打开。",
    filmBadge: "正在上映",
    filmTitle: "The Final Show",
    filmMeta: "Disney+ · 2025 年 12 月 12 日起",
    filmBody:
      "导演 Glenn Weiss 在温哥华拍下完整终场，第一次把 The Tortured Poets Department 舞台段落收进电影。没有新票可抢的日子里，这是离现场最近的座位。",
    show1City: "伦敦",
    show1Venue: "Wembley Stadium",
    show1Date: "2024 年 6 月 & 8 月",
    show1Note: "温布利八场连开，创下该球场单一艺人纪录。",
    show2City: "东京",
    show2Venue: "Tokyo Dome",
    show2Date: "2024 年 2 月 7–10 日",
    show2Note: "巨蛋四夜，东亚站把友谊手链做成一整座城的方言。",
    show3City: "新加坡",
    show3Venue: "National Stadium",
    show3Date: "2024 年 3 月 2–9 日",
    show3Note: "东南亚唯一一站，六场夜灯把国家体育场唱成港口。",
    upcomingTitle: "下一场还在路上",
    upcomingBody:
      "截至 2026 年 8 月，官方尚未公布新巡演日程。第十二张专辑《The Life of a Showgirl》已在 2025 年 10 月 3 日发行。传闻下一轮巡回可能要到 2027 年——在那之前，我们把旧灯留下。",
    whyKicker: "给她的信",
    whyTitle: "我们为什么爱 Taylor Swift",
    whyLead:
      "不是因为完美。是因为她把成长、愤怒、温柔和玩笑都写成可以跟唱的句子，让陌生人在同一段副歌里认出自己。",
    reason1Title: "她把日记写成歌",
    reason1Body:
      "从 Fifteen 到 All Too Well，她从不把细节藏起来。停车场、红色围巾、厨房里的争吵——那些本来只属于一个人的夜晚，被写得足够精确，于是也变成了我们的。听她的歌，像拆开一封写给过去自己的信。",
    reason2Title: "每一个时代都是一次长大",
    reason2Body:
      "Fearless 的金发、Red 的 intra、1989 的城市、Reputation 的盔甲、Folklore 的森林、Midnights 的钟点。她允许自己变，也允许听众变。爱她，是被允许和旧的自己告别，而不必假装从来没爱过。",
    reason3Title: "手链把陌生人变成同伴",
    reason3Body:
      "时代巡回让友谊手链变成世界语。排队时交换一串珠子，歌单就多了一个人。她把大型体育场唱成客厅，把粉丝之间的善意做成可佩戴的东西。这不只是一场秀，是一场持续了两年的见面会。",
    reason4Title: "她把故事拿回自己手里",
    reason4Body:
      "Taylor’s Version 不只是重录。是一个被卖掉版权的女孩，决定把声音再唱一遍，直到它重新属于她。热爱她，也是热爱那种不肯把叙事交给别人的倔强——以及她始终把听众当成同谋，而不是观众。",
    quote:
      "我十三岁那年 Fearless 发行。现在我已经三十出头。她没有把我们留在原地，她带着我们一起往前走。",
    quoteAttr: "一位听了十七年的霉粉",
    footerNote: "非官方粉丝站点 · 与泰勒·斯威夫特本人或所属厂牌无关",
    footerRights: "为热爱她的人而做",
    loginTitle: "欢迎回来",
    loginLead: "登录后即可继续。你的身份只用于这个小站。",
    loginGoogle: "使用 Google 继续",
    loginX: "使用 X 继续",
    loginDisabled: "登录已关闭。",
    loginBack: "返回论坛",
  },
  en: {
    brand: "The Swift Forum",
    brandMark: "TS",
    navConcerts: "Recent concerts",
    navWhy: "Why we love her",
    signIn: "Sign in",
    signOut: "Sign out",
    langEn: "EN",
    langZh: "中文",
    langAria: "Switch language",
    heroKicker: "A Swiftie room",
    heroTitle: "For those who love her",
    heroLead:
      "The lights from The Eras Tour are still warm. This is a small place for the recent shows — and for the reasons we keep coming back to Taylor Swift.",
    heroCtaConcerts: "Recent concerts",
    heroCtaWhy: "Why we love her",
    concertsKicker: "The Eras Tour",
    concertsTitle: "Recent concerts",
    concertsLead:
      "The Eras Tour took its last bow in Vancouver on December 8, 2024. One hundred forty-nine shows later, the wristbands still glow. No 2026 dates are on the books — but the final night now lives as a film we can walk back into.",
    concertsStatShows: "shows",
    concertsStatCities: "cities",
    concertsStatCountries: "countries",
    concertsStatContinents: "continents",
    featuredBadge: "Finale",
    featuredCity: "Vancouver",
    featuredVenue: "BC Place Stadium",
    featuredDate: "December 8, 2024",
    featuredTitle: "The last night of an era",
    featuredBody:
      "After twenty-one months and five continents, Taylor closed the book in a Vancouver rain night. Surprise songs, the full Tortured Poets set, Long Live sung like a vow. The finale was not an ending so much as a handing-back. In December 2025, Disney+ opened the lights again with the docuseries The End of an Era and the concert film The Final Show.",
    filmBadge: "Now streaming",
    filmTitle: "The Final Show",
    filmMeta: "Disney+ · from December 12, 2025",
    filmBody:
      "Glenn Weiss filmed the Vancouver closer in full, folding The Tortured Poets Department into a concert movie for the first time. On days with no tickets left to chase, this is the closest seat.",
    show1City: "London",
    show1Venue: "Wembley Stadium",
    show1Date: "June & August 2024",
    show1Note: "Eight nights at Wembley — a record for a single artist at the stadium.",
    show2City: "Tokyo",
    show2Venue: "Tokyo Dome",
    show2Date: "February 7–10, 2024",
    show2Note: "Four nights in the dome. Friendship bracelets became a whole city’s dialect.",
    show3City: "Singapore",
    show3Venue: "National Stadium",
    show3Date: "March 2–9, 2024",
    show3Note: "The only Southeast Asia stop. Six nights turned the stadium into a harbour of light.",
    upcomingTitle: "The next one is still on the way",
    upcomingBody:
      "As of August 2026, no new tour dates have been announced. Her twelfth album, The Life of a Showgirl, arrived on October 3, 2025. The next run is rumoured for 2027. Until then, we keep the old lights on.",
    whyKicker: "Letters to her",
    whyTitle: "Why we love Taylor Swift",
    whyLead:
      "Not because she is perfect. Because she writes growing up, anger, tenderness, and jokes into lines we can sing — and strangers recognise themselves in the same chorus.",
    reason1Title: "She writes like a diary",
    reason1Body:
      "From Fifteen to All Too Well, she never hides the particulars. Parking lots, a red scarf, a fight in a kitchen — nights that belonged to one person, written precisely enough to become ours. Listening feels like opening a letter to a former self.",
    reason2Title: "Every era is a growing-up",
    reason2Body:
      "Fearless gold, Red intra, 1989 cities, Reputation armour, Folklore woods, Midnights o’clock. She lets herself change, and she lets us change with her. Loving her is permission to leave an old self without pretending you never loved that self at all.",
    reason3Title: "Bracelets turn strangers into company",
    reason3Body:
      "The Eras Tour made friendship bracelets a world language. Trade a strand in line, and the setlist gains a person. She sang stadiums into living rooms, and made kindness something you could wear. Not just a show — a two-year greeting.",
    reason4Title: "She took the story back",
    reason4Body:
      "Taylor’s Version is not a re-record for its own sake. It is a girl whose catalogue was sold deciding to sing the songs again until they belonged to her. To love her is to love that stubbornness — and the way she treats listeners as co-conspirators, not an audience.",
    quote:
      "I was thirteen when Fearless came out. I am in my thirties now. She did not leave us where we were. She walked us forward.",
    quoteAttr: "A Swiftie of seventeen years",
    footerNote: "An unofficial fan site · not affiliated with Taylor Swift or her labels",
    footerRights: "Made for people who love her",
    loginTitle: "Welcome back",
    loginLead: "Sign in to continue. Your account is only used on this little site.",
    loginGoogle: "Continue with Google",
    loginX: "Continue with X",
    loginDisabled: "Sign-in is disabled.",
    loginBack: "Back to the forum",
  },
} as const;

export type Copy = (typeof copy)[Lang];
